version: '3.8'

services:
  backend:
    image: markjnt/palliroute-backend
    container_name: palliroute-backend
    volumes:
      - ./backend/data:/backend/data
    environment:
      - SECRET_KEY=your_secret_key_here
      - GOOGLE_MAPS_API_KEY=your-google-maps-api-key-here
      - CORS_ORIGINS=http://localhost:3000,http://192.168.1.100:3000
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    image: markjnt/palliroute-frontend
    container_name: palliroute-frontend
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 