"""new schedule and capacity model

Revision ID: 0e289ccdf15e
Revises: 2617ea0da3cb
Create Date: 2026-01-21 13:07:39.443860

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0e289ccdf15e"
down_revision = "2617ea0da3cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shift_definitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("area", sa.String(length=20), nullable=False),
        sa.Column("time_of_day", sa.String(length=10), nullable=False),
        sa.Column("is_weekday", sa.Boolean(), nullable=False),
        sa.Column("is_weekend", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "employee_capacities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("capacity_type", sa.String(length=50), nullable=False),
        sa.Column("month", sa.String(length=7), nullable=False),
        sa.Column("max_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "employee_id", "capacity_type", "month", name="unique_employee_capacity_month"
        ),
    )
    op.create_table(
        "shift_instances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shift_definition_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("calendar_week", sa.Integer(), nullable=False),
        sa.Column("month", sa.String(length=7), nullable=False),
        sa.ForeignKeyConstraint(
            ["shift_definition_id"],
            ["shift_definitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("shift_definition_id", "date", name="unique_shift_per_day"),
    )
    op.create_table(
        "assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("shift_instance_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shift_instance_id"],
            ["shift_instances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "employee_id", "shift_instance_id", name="unique_employee_shift_instance"
        ),
    )
    op.drop_table("oncall_assignments")
    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.drop_column("oncall_nursing_weekend")
        batch_op.drop_column("oncall_doctors_weekday")
        batch_op.drop_column("oncall_doctors_weekend")
        batch_op.drop_column("weekend_services_nursing")
        batch_op.drop_column("oncall_nursing_weekday")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.add_column(sa.Column("oncall_nursing_weekday", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("weekend_services_nursing", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("oncall_doctors_weekend", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("oncall_doctors_weekday", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("oncall_nursing_weekend", sa.INTEGER(), nullable=True))

    op.create_table(
        "oncall_assignments",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("employee_id", sa.INTEGER(), nullable=False),
        sa.Column("date", sa.DATE(), nullable=False),
        sa.Column("duty_type", sa.VARCHAR(length=50), nullable=False),
        sa.Column("area", sa.VARCHAR(length=50), nullable=True),
        sa.Column("calendar_week", sa.INTEGER(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date", "duty_type", "area", name=op.f("unique_date_duty_area")),
    )
    op.drop_table("assignments")
    op.drop_table("shift_instances")
    op.drop_table("employee_capacities")
    op.drop_table("shift_definitions")
    # ### end Alembic commands ###
