"""init

Revision ID: 0f82a595d983
Revises:
Create Date: 2025-11-23 18:06:01.902673

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0f82a595d983"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("street", sa.String(length=200), nullable=False),
        sa.Column("zip_code", sa.String(length=20), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("function", sa.String(length=100), nullable=False),
        sa.Column("work_hours", sa.Float(), nullable=False),
        sa.Column("area", sa.String(length=50), nullable=True),
        sa.Column("alias", sa.String(length=500), nullable=True),
        sa.Column("oncall_nursing_weekday", sa.Integer(), nullable=True),
        sa.Column("oncall_nursing_weekend_day", sa.Integer(), nullable=True),
        sa.Column("oncall_nursing_weekend_night", sa.Integer(), nullable=True),
        sa.Column("oncall_doctors_weekday", sa.Integer(), nullable=True),
        sa.Column("oncall_doctors_weekend", sa.Integer(), nullable=True),
        sa.Column("weekend_services_nursing", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "patients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("street", sa.String(length=200), nullable=False),
        sa.Column("zip_code", sa.String(length=20), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("phone1", sa.String(length=50), nullable=True),
        sa.Column("phone2", sa.String(length=50), nullable=True),
        sa.Column("calendar_week", sa.Integer(), nullable=True),
        sa.Column("area", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "system_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "appointments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=True),
        sa.Column("origin_employee_id", sa.Integer(), nullable=True),
        sa.Column("tour_employee_id", sa.Integer(), nullable=True),
        sa.Column("weekday", sa.String(length=20), nullable=False),
        sa.Column("time", sa.Time(), nullable=True),
        sa.Column("visit_type", sa.String(length=10), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("info", sa.String(length=200), nullable=True),
        sa.Column("area", sa.String(length=50), nullable=False),
        sa.Column("calendar_week", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["origin_employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tour_employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "employee_planning",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("weekday", sa.String(length=20), nullable=False),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.Column("custom_text", sa.String(length=200), nullable=True),
        sa.Column("replacement_id", sa.Integer(), nullable=True),
        sa.Column("calendar_week", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["replacement_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "employee_id", "weekday", "calendar_week", name="unique_employee_weekday_week"
        ),
    )
    op.create_table(
        "oncall_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("duty_type", sa.String(length=50), nullable=False),
        sa.Column("area", sa.String(length=50), nullable=True),
        sa.Column("calendar_week", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date", "duty_type", "area", name="unique_date_duty_area"),
    )
    op.create_table(
        "routes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=True),
        sa.Column("weekday", sa.String(length=20), nullable=False),
        sa.Column("route_order", sa.Text(), nullable=False),
        sa.Column("total_duration", sa.Integer(), nullable=False),
        sa.Column("total_distance", sa.Float(), nullable=True),
        sa.Column("polyline", sa.Text(), nullable=True),
        sa.Column("area", sa.String(length=50), nullable=False),
        sa.Column("calendar_week", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("routes")
    op.drop_table("oncall_assignments")
    op.drop_table("employee_planning")
    op.drop_table("appointments")
    op.drop_table("system_info")
    op.drop_table("patients")
    op.drop_table("employees")
    # ### end Alembic commands ###
