"""add oncall_nursing_weekend

Revision ID: 2617ea0da3cb
Revises: 0f82a595d983
Create Date: 2025-12-15 18:36:39.952669

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2617ea0da3cb"
down_revision = "0f82a595d983"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.add_column(sa.Column("oncall_nursing_weekend", sa.Integer(), nullable=True))
        batch_op.drop_column("oncall_nursing_weekend_day")
        batch_op.drop_column("oncall_nursing_weekend_night")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.add_column(sa.Column("oncall_nursing_weekend_night", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("oncall_nursing_weekend_day", sa.INTEGER(), nullable=True))
        batch_op.drop_column("oncall_nursing_weekend")

    # ### end Alembic commands ###
