"""create oncall_assignments table

Revision ID: 879d4bf95ff8
Revises: eee0e0703459
Create Date: 2025-11-23 17:12:29.714754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879d4bf95ff8'
down_revision = 'eee0e0703459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oncall_assignments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oncall_assignments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('duty_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('area', sa.VARCHAR(length=50), nullable=True),
    sa.Column('calendar_week', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'duty_type', 'area', name=op.f('unique_date_duty_area'))
    )
    # ### end Alembic commands ###
