"""add time account to employee

Revision ID: 8ed588aa3a27
Revises: cf5f9624b49e
Create Date: 2026-01-31 16:08:41.674141

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8ed588aa3a27"
down_revision = "cf5f9624b49e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.add_column(sa.Column("time_account", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.drop_column("time_account")

    # ### end Alembic commands ###
