"""remove month from capacity

Revision ID: cf5f9624b49e
Revises: 0e289ccdf15e
Create Date: 2026-01-25 15:19:45.479177

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cf5f9624b49e"
down_revision = "0e289ccdf15e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("employee_capacities", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("unique_employee_capacity_month"), type_="unique")
        batch_op.create_unique_constraint(
            "unique_employee_capacity", ["employee_id", "capacity_type"]
        )
        batch_op.drop_column("month")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("employee_capacities", schema=None) as batch_op:
        batch_op.add_column(sa.Column("month", sa.VARCHAR(length=7), nullable=False))
        batch_op.drop_constraint("unique_employee_capacity", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("unique_employee_capacity_month"), ["employee_id", "capacity_type", "month"]
        )

    # ### end Alembic commands ###
