"""create oncall_assignments table

Revision ID: d5cf366eb0da
Revises: 879d4bf95ff8
Create Date: 2025-11-23 17:14:32.266249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5cf366eb0da'
down_revision = '879d4bf95ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oncall_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duty_type', sa.String(length=50), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('calendar_week', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'duty_type', 'area', name='unique_date_duty_area')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oncall_assignments')
    # ### end Alembic commands ###
