"""Add Rufbereitschaft fields to employees

Revision ID: eee0e0703459
Revises: 
Create Date: 2025-11-20 17:18:49.405957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee0e0703459'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oncall_nursing_weekday', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('oncall_nursing_weekend_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('oncall_nursing_weekend_night', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('oncall_doctors_weekday', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('oncall_doctors_weekend', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weekend_services_nursing', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('weekend_services_nursing')
        batch_op.drop_column('oncall_doctors_weekend')
        batch_op.drop_column('oncall_doctors_weekday')
        batch_op.drop_column('oncall_nursing_weekend_night')
        batch_op.drop_column('oncall_nursing_weekend_day')
        batch_op.drop_column('oncall_nursing_weekday')

    # ### end Alembic commands ###
