name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/backend.Dockerfile
          platforms: linux/amd64,linux/arm64
          # Für noch schnellere Builds: nur linux/amd64 verwenden
          # platforms: linux/amd64
          push: true
          tags: markjnt/palliroute-backend
          cache-from: |
            type=registry,ref=docker.io/markjnt/palliroute-backend:buildcache
          cache-to: |
            type=registry,ref=docker.io/markjnt/palliroute-backend:buildcache,mode=max

  build-frontend-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Frontend-Web Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/frontend_web.Dockerfile
          platforms: linux/amd64,linux/arm64
          # Für noch schnellere Builds: nur linux/amd64 verwenden
          # platforms: linux/amd64
          push: true
          tags: markjnt/palliroute-frontend-web
          cache-from: |
            type=registry,ref=docker.io/markjnt/palliroute-frontend-web:buildcache
          cache-to: |
            type=registry,ref=docker.io/markjnt/palliroute-frontend-web:buildcache,mode=max

  build-frontend-pwa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Frontend-PWA Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/frontend_pwa.Dockerfile
          platforms: linux/amd64,linux/arm64
          # Für noch schnellere Builds: nur linux/amd64 verwenden
          # platforms: linux/amd64
          push: true
          tags: markjnt/palliroute-frontend-pwa
          cache-from: |
            type=registry,ref=docker.io/markjnt/palliroute-frontend-pwa:buildcache
          cache-to: |
            type=registry,ref=docker.io/markjnt/palliroute-frontend-pwa:buildcache,mode=max

  deploy:
    runs-on: self-hosted
    needs: [build-backend, build-frontend-web, build-frontend-pwa]
    defaults:
      run:
        working-directory: ~/PalliRoute
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Stop existing containers
        run: docker compose down
      - name: Remove old images
        run: docker rmi $(docker images -q) -f
      - name: Pull latest images
        run: docker compose pull
      - name: Start services
        run: docker compose up -d
      - name: Clean up old images
        run: docker image prune -f